config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static_pages#index'
  resources :courses, only: [:index, :show]
  namespace :instructor do 
  	resources :courses, only: [:new, :create, :show]
  end 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord
	belongs_to :user

	validates :title, presence: true
	validates :description, presence: true
	validates :cost, presence: true, numericality: {greater_than_or_equal_to: 0}
end

app/models/user.rb
class User < ApplicationRecord
	has_many :courses
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable         
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController

	def index 
		@courses = Course.all
	end 

	def show 
		@course = Course.find(params[:id])
	end 
end

app/controllers/instructor/courses_controller.rb
class Instructor::CoursesController < ApplicationController
	before_action :authenticate_user!

	def new 
		@course = Course.new
	end 

	def create
		@course = current_user.courses.create(course_params)
		if @course.valid?
			redirect_to instructor_course_path(@course)
		else
			render :new, status: :unprocessable_entity 
		end 
	end 

	def show 
		@course = Course.find(params[:id])
	end 

	private

	def course_params
		params.require(:course).permit(:title, :description, :cost)
	end 
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

	def index
	end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/instructor/courses_helper.rb
module Instructor::CoursesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/courses/index.html.erb
<br />
<div class="booyah-box col-10 offset-1">
	<h1>All Courses</h1>


<br />
	<% @courses.each do |course| %>
		<h2>
			<%= link_to course.title, course_path(course) %>		
		</h2>
		<div class="row">
			<div class="col-sm-8 col-12">
				<p><%= course.description %></p>
			</div>
			<div class="col-sm-4 col-12">
				<%= link_to 'Learn More', course_path(course), class: 'btn btn-primary btn-large' %>
			</div>
		</div>
		<br class="clr" />
	<% end %>
	<br />
</div>

app/views/courses/show.html.erb
<br />

<div class="booyah-box col-10 offset-1">
  <h1><%= @course.title %></h1>
  <br />
  <div class="row">
    <div class="col-sm-4 col-12 text-center">
      <span class="badge badge-default">
        <%= number_to_currency @course.cost %>
      </span>

      <% if current_user && current_user == @course.user %>
        <br />
        <br />
        <%= link_to 'Administer', instructor_course_path(@course), class: 'btn btn-danger btn-large' %>
      <% end %>
    </div>

    <div class="col-sm-8 col-12">
      <%= @course.description %>
    </div>
  </div>
</div>

app/views/instructor/courses/new.html.erb
<br /><br />
	<div class="booyah-box col-10 offset-1">
		
		<h1>Add a new Course</h1>
		
		<br />
		<%= simple_form_for @course, url: instructor_courses_path do |f| %>
			<%= f.input :title %>
			<%= f.input :description %>
			<%= f.input :cost %>
			<br />
			<%= f.submit "Create", class: "btn btn-primary" %>
			<br />
		<% end %>
    <br />

	</div>

app/views/instructor/courses/show.html.erb
<br />
	<div class="booyah-box col-10 offset-1">
		<h1><%= @course.title %></h1>
	</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
    <title>Courses</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <div id="flex-content-container">
    <nav class="navbar navbar-expand-lg navbar-inverse bg-dark">
        <%= link_to 'courses', root_path, class: 'navbar-brand' %>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <%= link_to 'See All Courses', courses_path, class: 'nav-link' %>
                </li>
                <ul class="navbar-nav float-right">
                    <% if user_signed_in? %>
                    <li class="nav-item">
                        <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: 'nav-link' %>
                    </li>
                    <% else %>
                    <li class="nav-item">
                        <%= link_to 'Sign in', new_user_session_path, class: 'nav-link' %>
                    </li>
                    <li class="nav-item">
                        <%= link_to 'Sign up', new_user_registration_path, class: 'nav-link' %>
                    </li>
                    <% end %>
                </ul>
            </ul>
        </div>
    </nav>

    <% if notice.present? %>
    <p class="alert alert-info">
        <%= notice %>
    </p>
    <% end %>
    <% if notice.present? %>
    <p class="alert alert-danger">
        <%= alert %>
    </p>
    <% end %>

    <%= yield %>
  </div>

  <div id="footer">
    <div class="container">
      <b>Administration</b>
      <br />
      <%= link_to 'Create a Course', new_instructor_course_path %>
    </div>
  </div>

</body>

</html>

app/views/static_pages/index.html.erb
<div class="hero">
	<div class="frosty col-10 offset-1 text-center">
		<br /><br /><br />
		<h1>training, simplified</h1>
		<p>Please Sigin to get started, or click below to learn more.</p>
		<br /><br /><br />
	</div>
</div>